[project]
name = "python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "graphviz>=0.21",
    "numpy>=2.4.2",
    "psutil>=7.2.2",
    "psutils>=3.3.14",
    "rich>=14.3.1",
    "treelib>=1.8.0",
]
